import React,{useState,useEffect} from 'react';
import {View,Text,ScrollView,TouchableOpacity,StyleSheet,Alert,RefreshControl,Linking} from 'react-native';
const API='https://flashdrop-backend-production.up.railway.app';
export default function MeusServicosScreen({motoboy}){
  const [pedidos,setPedidos]=useState([]);
  const [refreshing,setRefreshing]=useState(false);
  useEffect(()=>{load();const i=setInterval(load,15000);return()=>clearInterval(i);},[]);
  async function load(){try{const r=await fetch(API+'/api/motoboy/meus-servicos?id='+motoboy.id);if(r.ok)setPedidos(await r.json());}catch(e){}}
  async function concluir(id){Alert.alert('Confirmar','Marcar como concluida?',[{text:'Cancelar',style:'cancel'},{text:'Confirmar',onPress:async()=>{try{const r=await fetch(API+'/api/pedidos/concluir',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pedidoId:id,motoboyId:motoboy.id})});const d=await r.json();if(d.success){Alert.alert('Entrega concluida!');load();}else Alert.alert('Erro',d.message||'Tente novamente');}catch(e){Alert.alert('Erro','Sem conexao');}}}]);}
  const onRefresh=async()=>{setRefreshing(true);await load();setRefreshing(false);};
  return(<View style={s.c}><View style={s.h}><Text style={s.t}>Meus Servicos</Text></View><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor='#ff6b00'/>}>{pedidos.length===0?<Text style={s.v}>Nenhum servico em andamento</Text>:pedidos.map(p=>(<View key={p.id} style={s.card}><View style={s.row}><Text style={s.loja}>{p.store_name}</Text></View><Text style={s.lbl}>Entrega:</Text><Text style={s.val}>{p.delivery_address}</Text><Text style={s.lbl}>Taxa:</Text><Text style={[s.val,{color:'#f0c040'}]}>R$ {parseFloat(p.delivery_fee||0).toFixed(2)}</Text><View style={s.btns}><TouchableOpacity style={s.bm} onPress={()=>Linking.openURL('https://maps.google.com/?q='+encodeURIComponent(p.delivery_address))}><Text style={s.bmt}>Abrir Maps</Text></TouchableOpacity><TouchableOpacity style={s.bc} onPress={()=>concluir(p.id)}><Text style={s.bct}>Concluido</Text></TouchableOpacity></View></View>))}<View style={{height:20}}/></ScrollView></View>);
}
const s=StyleSheet.create({c:{flex:1,backgroundColor:'#0f0f0f'},h:{padding:20,paddingTop:50,backgroundColor:'#1a1a1a',borderBottomWidth:1,borderBottomColor:'#2a2a2a'},t:{color:'#fff',fontSize:22,fontWeight:'bold'},v:{color:'#666',textAlign:'center',padding:40},card:{margin:16,marginBottom:0,backgroundColor:'#1a1a1a',padding:16,borderRadius:14,borderWidth:1,borderColor:'#2a2a2a'},row:{flexDirection:'row',justifyContent:'space-between',marginBottom:12},loja:{color:'#fff',fontWeight:'bold',fontSize:17},lbl:{color:'#888',fontSize:12,marginTop:8},val:{color:'#fff',fontSize:14,marginTop:2},btns:{flexDirection:'row',gap:10,marginTop:16},bm:{flex:1,backgroundColor:'#1a2a3a',padding:12,borderRadius:10,alignItems:'center'},bmt:{color:'#4da6ff',fontWeight:'600'},bc:{flex:1,backgroundColor:'#1a3a1a',padding:12,borderRadius:10,alignItems:'center'},bct:{color:'#00d26a',fontWeight:'600'}});